age_population_year #9
njtierney/conmat pull request #63
Opened 2022-02-17 01:58 UTC by aarathybabu97

2022-02-18 04:04 UTC, aarathybabu97 commented
```r
library(conmat)
 world_data <- socialmixr::wpp_age()
 age_population(
  data = world_data,
 country_col = country,
 country = "Asia",
  age_col = lower.age.limit,
  year_col = year,
  year = 2010
)%>%
   dplyr::arrange(lower.age.limit)%>%
   head(5)
#>   country year population lower.age.limit upper.age.limit
#> 1    Asia 2010  360336208               0               4
#> 2    Asia 2010  350780197               5               9
#> 3    Asia 2010  351260914              10              14
#> 4    Asia 2010  372841496              15              19
#> 5    Asia 2010  386404948              20              24

age_population(
  data = world_data,
  age_col = lower.age.limit,
  year_col = year,
  year = 2010
)%>%
  dplyr::arrange(lower.age.limit)%>%
  head(5)
#>       country year population lower.age.limit upper.age.limit
#> 1 Afghanistan 2010    5011447               0               4
#> 2      Africa 2010  165738403               0               4
#> 3     Albania 2010     158681               0               4
#> 4     Algeria 2010    3844982               0               4
#> 5      Angola 2010    4162211               0               4

age_population(
  data = world_data,
  country_col = country,
  country = "Australia",
  age_col = lower.age.limit
)%>%
  dplyr::arrange(lower.age.limit)%>%
  head(5)
#>     country year population lower.age.limit upper.age.limit
#> 1 Australia 1950     888741               0               4
#> 2 Australia 1955     993468               0               4
#> 3 Australia 1960    1094108               0               4
#> 4 Australia 1965    1163156               0               4
#> 5 Australia 1970    1247078               0               4

Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)
```

Note: 85+ ages are kept under 85-120 age group

2022-02-22 03:47 UTC, njtierney requested changes

2022-02-22 03:47 UTC, njtierney commented on R/check_args_age_population_year.R
> +    return(age_population_year_df)
Add braces around `else`:

```
else {
return(...)
}
```

2022-02-22 03:47 UTC, njtierney commented on R/age-population-year.R
> +        dplyr::mutate(age_group = cut({{ age_col }},
Add a linebreak here:

```
dplyr::mutate(
  age_group = ..,
  breaks = ...
  ...
  )
```

2022-02-22 03:47 UTC, njtierney commented on R/get_age_population_function.R
> +  max_bound <- max(pop_model%>%
move `pop_model` inside of `dplyr::pull`:

```
dplyr::pull(
  pop_model,
  {{ age_col }}
  )

```

2022-02-22 03:47 UTC, njtierney commented on R/separate_age_group.R
> +      tidyr::separate({{age_col}}, c("lower.age.limit", "upper.age.limit"), "[[:punct:]]", extra = "merge") %>%
Add line breaks and. indentation here:

```
tidyr::seprate(
  {{ age_col }},
 ...,
)
```

2022-02-22 03:47 UTC, njtierney commented on conmat.Rproj
> +AlwaysSaveHistory: No
Not sure how this changed - let's discuss

2022-02-22 03:47 UTC, njtierney commented on inst/old_age_population_year.R
> +  .args <- as.list(match.call()[-1])
I don't think `.args` is needed anymore?

2022-02-22 03:48 UTC, njtierney commented
Can you also ensure that these functions return a `tibble` instead of a `data.frame`

2022-03-16 01:59 UTC, njtierney requested changes

2022-03-16 01:59 UTC, njtierney commented on R/get_age_population_function.R
I remember you had made some changes to this, using `.data`, but I can't seem to find where those changes are in the other PRs

2022-03-21 03:34 UTC, njtierney approved these changes
Looks. good to me!

2022-03-21 03:40 UTC, merged