mess of code for `apply_vaccination.R` produces vaccinated matrix but…
njtierney/conmat pull request #67
Opened 2022-03-25 01:23 UTC by geryan

… needs to be tidied into function format.

@aarathybabu97 to tidy this into a working format - currently an irresponsible unworkable script...

2022-03-25 01:24 UTC, geryan commented
(don't merge until tidied)

2022-04-01 06:25 UTC, aarathybabu97 commented
```r

library(conmat)
#> 
#> Attaching package: 'conmat'
#> The following objects are masked _by_ '.GlobalEnv':
#> 
#>     estimate_setting_contacts, extrapolate_polymod
 vaccination_effect_example_data
#> # A tibble: 17 x 4
#>    age_band coverage acquisition transmission
#>    <chr>       <dbl>       <dbl>        <dbl>
#>  1 0-4         0           0            0    
#>  2 5-11        0.782       0.583        0.254
#>  3 12-15       0.997       0.631        0.295
#>  4 16-19       0.965       0.786        0.469
#>  5 20-24       0.861       0.774        0.453
#>  6 25-29       0.997       0.778        0.458
#>  7 30-34       0.998       0.803        0.493
#>  8 35-39       0.998       0.829        0.533
#>  9 40-44       0.999       0.841        0.551
#> 10 45-49       0.993       0.847        0.562
#> 11 50-54       0.999       0.857        0.579
#> 12 55-59       0.996       0.864        0.591
#> 13 60-64       0.998       0.858        0.581
#> 14 65-69       0.999       0.864        0.591
#> 15 70-74       0.999       0.867        0.597
#> 16 75-79       0.999       0.866        0.595
#> 17 80+         0.999       0.844        0.556
 ngm_NSW <- generate_ngm(state_name = "NSW", 
                         age_breaks = c(seq(0, 80, by = 5),Inf),
                         R_target = 1.5
                         ) 
 ngm_NSW$all
#>                [0,5)      [5,10)     [10,15)     [15,20)     [20,25)
#> [0,5)    0.105119565 0.051693794 0.018301115 0.012344944 0.020170646
#> [5,10)   0.068608738 0.279823500 0.074443568 0.022489704 0.018470817
#> [10,15)  0.037908084 0.092171499 0.435578743 0.089168659 0.029762839
#> [15,20)  0.036167362 0.038954418 0.114311912 0.463723946 0.099489031
#> [20,25)  0.078474660 0.047367627 0.056730985 0.164217927 0.355841672
#> [25,30)  0.174037458 0.092433247 0.056430963 0.075740930 0.216164488
#> [30,35)  0.237782934 0.181278569 0.094748947 0.062961456 0.106331493
#> [35,40)  0.172589301 0.215722690 0.160755032 0.083585470 0.074694250
#> [40,45)  0.089320176 0.139028650 0.173414083 0.124108253 0.077564100
#> [45,50)  0.058762317 0.071928631 0.112003714 0.136730382 0.107613395
#> [50,55)  0.057150198 0.047331989 0.056492106 0.088509790 0.117735406
#> [55,60)  0.062405481 0.044441675 0.034300132 0.041874127 0.075259885
#> [60,65)  0.055314317 0.045688228 0.028647336 0.022348932 0.033502438
#> [65,70)  0.036352001 0.036766933 0.026361758 0.016669137 0.016122111
#> [70,75)  0.020397410 0.022002373 0.019632750 0.014386688 0.011379212
#> [75,80)  0.010544998 0.011428000 0.011178321 0.010409274 0.009563331
#> [80,Inf) 0.006863074 0.008225662 0.008229906 0.008529428 0.010440610
#>              [25,30)     [30,35)    [35,40)    [40,45)    [45,50)    [50,55)
#> [0,5)    0.040827924 0.054568563 0.03958914 0.02285643 0.01883850 0.02133527
#> [5,10)   0.031791489 0.063424572 0.08214487 0.05807597 0.03678757 0.03286735
#> [10,15)  0.027034826 0.044723268 0.08276140 0.09864450 0.06873067 0.04619231
#> [15,20)  0.041762231 0.040115330 0.05966314 0.09600786 0.10411747 0.07335998
#> [20,25)  0.147143683 0.080589849 0.07775703 0.09851643 0.13660264 0.14248669
#> [25,30)  0.370724616 0.199692714 0.13551791 0.12274320 0.13736642 0.17851697
#> [30,35)  0.234284402 0.340293388 0.22669651 0.16364867 0.13734763 0.15247877
#> [35,40)  0.119080307 0.200908178 0.28200189 0.21050120 0.14660475 0.12394650
#> [40,45)  0.081058229 0.103646931 0.16225570 0.22832891 0.17584568 0.12154226
#> [45,50)  0.082248591 0.077779789 0.09472019 0.14212208 0.20874924 0.16488064
#> [50,55)  0.104485823 0.079666014 0.07322202 0.08543103 0.13029698 0.21449673
#> [55,60)  0.106285265 0.096237279 0.07255062 0.06187200 0.07086463 0.12617193
#> [60,65)  0.062057704 0.088579751 0.08168306 0.05590877 0.04424561 0.05833971
#> [65,70)  0.024618671 0.045316781 0.06684441 0.05752257 0.03609761 0.03098885
#> [70,75)  0.011738155 0.017758023 0.03337584 0.04651249 0.03739811 0.02475502
#> [75,80)  0.008520691 0.008883585 0.01363228 0.02395430 0.03060585 0.02510187
#> [80,Inf) 0.012172600 0.012465506 0.01306234 0.01689492 0.02508046 0.03253169
#>             [55,60)    [60,65)    [65,70)    [70,75)    [75,80)   [80,Inf)
#> [0,5)    0.02411623 0.02183090 0.01573257 0.01351693 0.01585976 0.01757519
#> [5,10)   0.03217978 0.03277361 0.02703191 0.02022905 0.01993994 0.02756727
#> [10,15)  0.03490682 0.03221436 0.03267022 0.02758998 0.02327147 0.03067676
#> [15,20)  0.04504865 0.03178460 0.03140717 0.03253355 0.02899572 0.03137648
#> [20,25)  0.09880358 0.05777798 0.04270228 0.04469665 0.04519700 0.04599102
#> [25,30)  0.18024974 0.11869501 0.06845267 0.05741564 0.05828658 0.06408175
#> [30,35)  0.19078235 0.17899505 0.11399899 0.07543563 0.06423432 0.07197008
#> [35,40)  0.13790145 0.16182228 0.14581481 0.10374815 0.07261078 0.06639473
#> [40,45)  0.10285612 0.10774817 0.12063707 0.11848915 0.09145437 0.06484876
#> [45,50)  0.11155270 0.08782508 0.08625768 0.10264021 0.10783654 0.08474812
#> [50,55)  0.16798442 0.10539098 0.07650497 0.07851369 0.09656998 0.11420253
#> [55,60)  0.22891435 0.16929796 0.09773423 0.07239106 0.07467371 0.12180878
#> [60,65)  0.12215646 0.22316498 0.15549199 0.09060906 0.06502646 0.09452901
#> [65,70)  0.04821369 0.10556020 0.18827210 0.13340994 0.07343390 0.06098357
#> [70,75)  0.02440572 0.03996615 0.08584034 0.15111378 0.10203921 0.04899723
#> [75,80)  0.01859135 0.01968697 0.03156120 0.06768198 0.11351025 0.05799354
#> [80,Inf) 0.03226154 0.02766517 0.02625227 0.03608725 0.06836967 0.11055769
 ngmNSW_vaccination<- apply_vaccination(ngm = ngm_NSW,
                                          data=vaccination_effect_example_data,
                                          coverage_col=coverage,
                                          acquisition_col=acquisition,
                                          transmission_col=transmission)
 
 ngmNSW_vaccination$all
#>                [0,5)      [5,10)      [10,15)      [15,20)      [20,25)
#> [0,5)    0.105071450 0.041268418 0.0128581967 0.0067396830 0.0122468731
#> [5,10)   0.037491505 0.121901698 0.0285379582 0.0067096702 0.0061537505
#> [10,15)  0.014129531 0.027373154 0.1141941394 0.0181314192 0.0067875501
#> [15,20)  0.008736699 0.007504315 0.0194041756 0.0613715762 0.0146844355
#> [20,25)  0.026149702 0.012608027 0.0132961158 0.0299890509 0.0723011826
#> [25,30)  0.039169067 0.016664757 0.0089470298 0.0093703302 0.0297074724
#> [30,35)  0.047337345 0.028972562 0.0133275832 0.0068928464 0.0129615088
#> [35,40)  0.029586187 0.029741783 0.0195262877 0.0078672139 0.0078399272
#> [40,45)  0.014192723 0.017805248 0.0196106756 0.0108722203 0.0075614781
#> [45,50)  0.009220715 0.009078389 0.0125197289 0.0118664251 0.0103733582
#> [50,55)  0.008234127 0.005454506 0.0057618296 0.0070221752 0.0103697088
#> [55,60)  0.008832631 0.005024148 0.0034118606 0.0032441593 0.0064820816
#> [60,65)  0.008036111 0.005309878 0.0029278865 0.0017719525 0.0029643595
#> [65,70)  0.004989979 0.004047441 0.0025589497 0.0012531102 0.0013472239
#> [70,75)  0.002691888 0.002337143 0.0018404956 0.0010454330 0.0009151580
#> [75,80)  0.001396409 0.001219274 0.0010506820 0.0007584711 0.0007705162
#> [80,Inf) 0.001065868 0.001046808 0.0009224368 0.0007393222 0.0010046205
#>               [25,30)      [30,35)      [35,40)     [40,45)     [45,50)
#> [0,5)    0.0220890624 0.0276252318 0.0184870888 0.010280588 0.008314146
#> [5,10)   0.0093876135 0.0175336172 0.0209771351 0.014294663 0.008889493
#> [10,15)  0.0054472305 0.0084153215 0.0144016364 0.016544339 0.011323272
#> [15,20)  0.0054821537 0.0048801532 0.0067292264 0.010438635 0.011112733
#> [20,25)  0.0267702234 0.0135854193 0.0120765313 0.014831801 0.020123966
#> [25,30)  0.0455510264 0.0228832528 0.0141503255 0.012432422 0.013691311
#> [30,35)  0.0254001770 0.0346424824 0.0210507664 0.014540695 0.012085576
#> [35,40)  0.0110819524 0.0175438674 0.0227988639 0.016220235 0.011157849
#> [40,45)  0.0070184204 0.0083573009 0.0121581308 0.016451352 0.012463620
#> [45,50)  0.0070541969 0.0061834914 0.00 [...]

2022-04-02 23:55 UTC, aarathybabu97 commented
```r
library(conmat)
#> 
#> Attaching package: 'conmat'
#> The following objects are masked _by_ '.GlobalEnv':
#> 
#>     estimate_setting_contacts, extrapolate_polymod
 vaccination_effect_example_data
#> # A tibble: 17 x 4
#>    age_band coverage acquisition transmission
#>    <chr>       <dbl>       <dbl>        <dbl>
#>  1 0-4         0           0            0    
#>  2 5-11        0.782       0.583        0.254
#>  3 12-15       0.997       0.631        0.295
#>  4 16-19       0.965       0.786        0.469
#>  5 20-24       0.861       0.774        0.453
#>  6 25-29       0.997       0.778        0.458
#>  7 30-34       0.998       0.803        0.493
#>  8 35-39       0.998       0.829        0.533
#>  9 40-44       0.999       0.841        0.551
#> 10 45-49       0.993       0.847        0.562
#> 11 50-54       0.999       0.857        0.579
#> 12 55-59       0.996       0.864        0.591
#> 13 60-64       0.998       0.858        0.581
#> 14 65-69       0.999       0.864        0.591
#> 15 70-74       0.999       0.867        0.597
#> 16 75-79       0.999       0.866        0.595
#> 17 80+         0.999       0.844        0.556
 ngm_NSW <- generate_ngm(state_name = "NSW", 
                         age_breaks = c(seq(0, 80, by = 5),Inf),
                         R_target = 1.5
                         ) 
 
 ngm_NSW$all
#>                [0,5)      [5,10)     [10,15)     [15,20)     [20,25)
#> [0,5)    0.105119565 0.051693794 0.018301115 0.012344944 0.020170646
#> [5,10)   0.068608738 0.279823500 0.074443568 0.022489704 0.018470817
#> [10,15)  0.037908084 0.092171499 0.435578743 0.089168659 0.029762839
#> [15,20)  0.036167362 0.038954418 0.114311912 0.463723946 0.099489031
#> [20,25)  0.078474660 0.047367627 0.056730985 0.164217927 0.355841672
#> [25,30)  0.174037458 0.092433247 0.056430963 0.075740930 0.216164488
#> [30,35)  0.237782934 0.181278569 0.094748947 0.062961456 0.106331493
#> [35,40)  0.172589301 0.215722690 0.160755032 0.083585470 0.074694250
#> [40,45)  0.089320176 0.139028650 0.173414083 0.124108253 0.077564100
#> [45,50)  0.058762317 0.071928631 0.112003714 0.136730382 0.107613395
#> [50,55)  0.057150198 0.047331989 0.056492106 0.088509790 0.117735406
#> [55,60)  0.062405481 0.044441675 0.034300132 0.041874127 0.075259885
#> [60,65)  0.055314317 0.045688228 0.028647336 0.022348932 0.033502438
#> [65,70)  0.036352001 0.036766933 0.026361758 0.016669137 0.016122111
#> [70,75)  0.020397410 0.022002373 0.019632750 0.014386688 0.011379212
#> [75,80)  0.010544998 0.011428000 0.011178321 0.010409274 0.009563331
#> [80,Inf) 0.006863074 0.008225662 0.008229906 0.008529428 0.010440610
#>              [25,30)     [30,35)    [35,40)    [40,45)    [45,50)    [50,55)
#> [0,5)    0.040827924 0.054568563 0.03958914 0.02285643 0.01883850 0.02133527
#> [5,10)   0.031791489 0.063424572 0.08214487 0.05807597 0.03678757 0.03286735
#> [10,15)  0.027034826 0.044723268 0.08276140 0.09864450 0.06873067 0.04619231
#> [15,20)  0.041762231 0.040115330 0.05966314 0.09600786 0.10411747 0.07335998
#> [20,25)  0.147143683 0.080589849 0.07775703 0.09851643 0.13660264 0.14248669
#> [25,30)  0.370724616 0.199692714 0.13551791 0.12274320 0.13736642 0.17851697
#> [30,35)  0.234284402 0.340293388 0.22669651 0.16364867 0.13734763 0.15247877
#> [35,40)  0.119080307 0.200908178 0.28200189 0.21050120 0.14660475 0.12394650
#> [40,45)  0.081058229 0.103646931 0.16225570 0.22832891 0.17584568 0.12154226
#> [45,50)  0.082248591 0.077779789 0.09472019 0.14212208 0.20874924 0.16488064
#> [50,55)  0.104485823 0.079666014 0.07322202 0.08543103 0.13029698 0.21449673
#> [55,60)  0.106285265 0.096237279 0.07255062 0.06187200 0.07086463 0.12617193
#> [60,65)  0.062057704 0.088579751 0.08168306 0.05590877 0.04424561 0.05833971
#> [65,70)  0.024618671 0.045316781 0.06684441 0.05752257 0.03609761 0.03098885
#> [70,75)  0.011738155 0.017758023 0.03337584 0.04651249 0.03739811 0.02475502
#> [75,80)  0.008520691 0.008883585 0.01363228 0.02395430 0.03060585 0.02510187
#> [80,Inf) 0.012172600 0.012465506 0.01306234 0.01689492 0.02508046 0.03253169
#>             [55,60)    [60,65)    [65,70)    [70,75)    [75,80)   [80,Inf)
#> [0,5)    0.02411623 0.02183090 0.01573257 0.01351693 0.01585976 0.01757519
#> [5,10)   0.03217978 0.03277361 0.02703191 0.02022905 0.01993994 0.02756727
#> [10,15)  0.03490682 0.03221436 0.03267022 0.02758998 0.02327147 0.03067676
#> [15,20)  0.04504865 0.03178460 0.03140717 0.03253355 0.02899572 0.03137648
#> [20,25)  0.09880358 0.05777798 0.04270228 0.04469665 0.04519700 0.04599102
#> [25,30)  0.18024974 0.11869501 0.06845267 0.05741564 0.05828658 0.06408175
#> [30,35)  0.19078235 0.17899505 0.11399899 0.07543563 0.06423432 0.07197008
#> [35,40)  0.13790145 0.16182228 0.14581481 0.10374815 0.07261078 0.06639473
#> [40,45)  0.10285612 0.10774817 0.12063707 0.11848915 0.09145437 0.06484876
#> [45,50)  0.11155270 0.08782508 0.08625768 0.10264021 0.10783654 0.08474812
#> [50,55)  0.16798442 0.10539098 0.07650497 0.07851369 0.09656998 0.11420253
#> [55,60)  0.22891435 0.16929796 0.09773423 0.07239106 0.07467371 0.12180878
#> [60,65)  0.12215646 0.22316498 0.15549199 0.09060906 0.06502646 0.09452901
#> [65,70)  0.04821369 0.10556020 0.18827210 0.13340994 0.07343390 0.06098357
#> [70,75)  0.02440572 0.03996615 0.08584034 0.15111378 0.10203921 0.04899723
#> [75,80)  0.01859135 0.01968697 0.03156120 0.06768198 0.11351025 0.05799354
#> [80,Inf) 0.03226154 0.02766517 0.02625227 0.03608725 0.06836967 0.11055769
 ngmNSW_vaccination<- apply_vaccination(ngm = ngm_NSW,
                                          data=vaccination_effect_example_data,
                                          coverage_col=coverage,
                                          acquisition_col=acquisition,
                                          transmission_col=transmission)
 
 ngmNSW_vaccination$all
#>                [0,5)      [5,10)      [10,15)      [15,20)      [20,25)
#> [0,5)    0.105119565 0.041415002 0.0129140338 0.0067641599 0.0123159846
#> [5,10)   0.037307371 0.121904202 0.0285645081 0.0067007543 0.0061326848
#> [10,15)  0.014066363 0.027400969 0.1140515044 0.0181295475 0.0067433186
#> [15,20)  0.008746376 0.007547226 0.0195068515 0.0614462808 0.0146904759
#> [20,25)  0.026213030 0.012676188 0.0133718797 0.0300561320 0.0725761479
#> [25,30)  0.039139432 0.016654027 0.0089551653 0.0093331268 0.0296828409
#> [30,35)  0.047224276 0.028843660 0.0132783275 0.0068514758 0.0128942435
#> [35,40)  0.029658387 0.029699475 0.0194931754 0.0078702620 0.0078373666
#> [40,45)  0.014348456 0.017892836 0.0196573202 0.0109239826 0.0076079154
#> [45,50)  0.009326892 0.009146588 0.0125445423 0.0118912583 0.0104292650
#> [50,55)  0.008227322 0.005459022 0.0057386918 0.0069816301 0.0103489716
#> [55,60)  0.008720562 0.004975439 0.0033822201 0.0032062119 0.0064214720
#> [60,65)  0.007937307 0.005252417 0.0029007093 0.0017571835 0.0029353598
#> [65,70)  0.004990615 0.004043919 0.0025537857 0.0012539020 0.0013514406
#> [70,75)  0.002731726 0.002360755 0.0018553573 0.0010557173 0.0009305154
#> [75,80)  0.001418637 0.001231727 0.0010611722 0.0007673087 0.0007855674
#> [80,Inf) 0.001082024 0.001038983 0.0009155824 0.0007368224 0.0010050633
#>               [25,30)      [30,35)      [35,40)     [40,45)     [45,50)
#> [0,5)    0.0222091435 0.0277106450 0.0185211257 0.010281976 0.008325577
#> [5,10)   0.0094037394 0.0175136584 0.0208971437 0.014206263 0.008840651
#> [10,15)  0.0054569261 0.0084272839 0.0143670985 0.016466111 0.011271156
#> [15,20)  0.0054937581 0.0049263562 0.0067500769 0.010444467 0.011127634
#> [20,25)  0.0267364605 0.0136701171 0.0121511868 0.014803508 0.020165768
#> [25,30)  0.0453521335 0.0228054224 0.0142580381 0.012417593 0.013652754
#> [30,35)  0.0253106042 0.0343196027 0.0210630243 0.014620603 0.012055179
#> [35,40)  0.0111313571 0.0175321585 0.0226713275 0.016272580 0.011133958
#> [40,45)  0.0070831627 0.0084550495 0.0121940183 0.016500028 0.012484041
#> [45,50)  0.0071013516 0.0062691537 0.0 [...]

2022-04-13 02:05 UTC, njtierney commented on R/apply_vaccination.R
> +#' @param data data set with location specific information on vaccine coverage, efficacy of acquisition/susceptibility and efficacy of transmission/infectiousness for the ordered age groups from lowe
change "data set" to "data frame"

2022-04-13 02:06 UTC, njtierney commented on R/apply_vaccination.R
> +#' vaccination_effect_example_data
Write a comment describing what "vaccination_effect_example_data" is

2022-04-13 04:27 UTC, njtierney requested changes
Add a test for `apply_vaccination` to ensure it returns the right output and class

2022-05-03 07:36 UTC, njtierney commented on R/apply_vaccination.R
> +ngm_vaccinated=Map('*',ngm,transmission_reduction_matrix)
Can you use `<-` instead of `=`, and also add a space around the `<-`

2022-05-03 07:36 UTC, njtierney commented on R/apply_vaccination.R
> +#' ngm_NSW <- generate_ngm(state_name = "NSW",
change to `ngm_nsw` instead of `NSW`

2022-05-03 07:36 UTC, njtierney commented on R/apply_vaccination.R
> +#' ngm_NSW_vacc <- apply_vaccination(ngm = ngm_NSW,
change `ngm_NSW` to `ngm_nsw`

2022-05-03 07:38 UTC, njtierney requested changes
Just a couple of super minor syntax changes, otherwise looks great!

2022-05-06 01:46 UTC, njtierney approved these changes

2022-05-06 01:46 UTC, njtierney commented
Looks good to me!

2022-05-06 01:46 UTC, merged